claude:
	export ANTHROPIC_BASE_URL=https://api.aicodemirror.com/api/claudecode
    export ANTHROPIC_API_KEY=sk-ant-api03-bsJy05u3CgyWHgyJwVog--h3D2U7KZWTtnQfH8Iuemi-qolI1mBncriCxENgw0thS5Fpy0HHKM1oOV5K3Mv2Og
    export ANTHROPIC_AUTH_TOKEN=""
